# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinfo',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
