# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0002_buildinfo_is_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_build_info', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionWorkerBuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_build_info', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StagingBuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_build_info', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StagingWorkerBuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_build_info', models.TextField()),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BuildInfo',
        ),
    ]
