# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0003_auto_20160527_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circleci_json', models.TextField()),
                ('branch', models.CharField(max_length=255)),
                ('commitor', models.CharField(max_length=255)),
                ('circleci_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerBuildInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('server_type', models.CharField(max_length=255)),
                ('is_success', models.BooleanField(default=False)),
                ('console_output', models.TextField()),
                ('build_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy_app.BuildInfo')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductionBuildInfo',
        ),
        migrations.DeleteModel(
            name='ProductionWorkerBuildInfo',
        ),
        migrations.DeleteModel(
            name='StagingBuildInfo',
        ),
        migrations.DeleteModel(
            name='StagingWorkerBuildInfo',
        ),
    ]
