# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0004_auto_20160531_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinfo',
            name='vcs_revision',
            field=models.TextField(default='0000000'),
        ),
    ]
