# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0005_buildinfo_vcs_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinfo',
            name='deployment_status',
            field=models.BooleanField(default=False),
        ),
    ]
