# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0006_buildinfo_deployment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildinfo',
            old_name='commitor',
            new_name='commiter',
        ),
        migrations.AlterField(
            model_name='buildinfo',
            name='vcs_revision',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='serverbuildinfo',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
