# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0007_auto_20160603_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinfo',
            name='circleci_url',
            field=models.URLField(max_length=255),
        ),
    ]
