# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy_app', '0008_auto_20160606_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverbuildinfo',
            name='server_type',
        ),
    ]
